name: modifiers
channels:
  - conda-forge
dependencies:
  - conda-forge::ipykernel=5.1.3
  - conda-forge::ipywidgets=7.5.1
  - conda-forge::nb_conda_kernels=2.2.2
  - conda-forge::nltk=3.4.4
  - conda-forge::notebook=6.0.1
  - conda-forge::numpy=1.17.3
  - conda-forge::pandas=0.25.2
  - conda-forge::python=3.7.3
  - conda-forge::requests=2.22.0
  - conda-forge::scikit-learn=0.21.3
  - conda-forge::scipy=1.3.1
  - conda-forge::tqdm=4.36.1
