name: modifiers
channels:
  - conda-forge
dependencies:
  - conda-forge::beautifulsoup4=4.8.2
  - conda-forge::gensim=3.8.1
  - conda-forge::ipykernel=5.1.4
  - conda-forge::ipywidgets=7.5.1
  - conda-forge::nb_conda_kernels=2.2.2
  - conda-forge::nltk=3.4.4
  - conda-forge::notebook=6.0.3
  - conda-forge::numpy=1.18.1
  - conda-forge::pandas=1.0.1
  - conda-forge::python=3.7.6
  - conda-forge::requests=2.22.0
  - conda-forge::scikit-learn=0.22.1
  - conda-forge::scipy=1.4.1
  - conda-forge::setuptools=45.2.0
  - conda-forge::tqdm=4.42.1
